---
title: "ProjectPresentation"
author: "Kyle Smith"
date: "2024-11-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(tidyverse)
library(ggplot2)
```

```{r}
data <- read_excel("C:\\Users\\myste\\Desktop\\Project.xlsx")

t.test(data$`Units Given in that day:`)

data$`Date:` <- as.Date(data$`Date:`)

ggplot(data, aes(x = `Date:`)) +
  geom_line(aes(y = `Units Given in that day:`, color = "Total Units"), size = 1) +
  
  geom_point(aes(y = `Units Given in that day:`, color = "Total Units"), size = 3) +
  geom_hline(aes(yintercept = 108, color = "108 units"), linetype = "dashed", size = 1) +
  
  scale_x_date(date_labels = "%d %b", date_breaks = "1 day") +
  
  labs(title = "Insulin Dosage Over Time",
       x = "Date",
       y = "Total Insulin Dosage (units)") +
  theme_minimal() +
  
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  
  scale_color_manual(values = c("Total Units" = "blue", "108 units" = "gray"))
```

